import { readFile, stat } from "node:fs/promises";
import path from "node:path";

/**
 * How one argv is actually started. On Windows `.cmd`/`.bat` command shims (`pnpm`, `npm`, `tsc`
 * …) cannot be spawned directly without a shell (Node refuses since CVE-2024-27980), and a shell
 * string would undo argv-based policy. Policy always classifies the ORIGINAL argv; this module
 * only decides how that already-approved argv is launched:
 *
 * 1. The program is resolved on PATH with PATHEXT (only `.com`/`.exe`/`.bat`/`.cmd`), never the
 *    current directory. A native executable is spawned by its absolute path.
 * 2. A shim generated by npm's or pnpm's cmd-shim (every line on a known form) is not run at all:
 *    its `node <script>` target is spawned directly with the argv, exactly as the shim would.
 * 3. Any other shim runs as `cmd.exe /d /v:off /s /c "<shim> <args>"` with every argument
 *    double-quoted (`"` doubled, `%` neutralized), so no argument can end cmd's quoting or expand
 *    a variable; CR, LF and NUL cannot cross cmd.exe and are refused.
 *
 * Other platforms spawn the argv unchanged.
 */
export interface LaunchPlan {
  readonly file: string;
  readonly args: readonly string[];
  readonly env: Readonly<Record<string, string>>;
  /** True only for the cmd.exe route: the command line is already quoted. */
  readonly verbatim: boolean;
  readonly via: "direct" | "node-shim" | "cmd-shim";
}

export interface LaunchOptions {
  readonly cwd: string;
  readonly env: Readonly<Record<string, string>>;
  readonly platform?: NodeJS.Platform;
}

export class UnsafeLaunchError extends Error {}

const RUNNABLE_EXTENSIONS = new Set([".com", ".exe", ".bat", ".cmd"]);
const DEFAULT_PATHEXT = ".COM;.EXE;.BAT;.CMD";

export async function planLaunch(argv: readonly [string, ...string[]], options: LaunchOptions): Promise<LaunchPlan> {
  const [program, ...args] = argv;
  const direct: LaunchPlan = { file: program, args, env: options.env, verbatim: false, via: "direct" };
  if ((options.platform ?? process.platform) !== "win32") return direct;
  const resolved = await resolveProgram(program, options);
  if (resolved === undefined) return direct;
  if (!isShim(resolved)) return { ...direct, file: resolved };
  const shim = await nodeShimTarget(resolved, options.env);
  if (shim !== undefined) return { file: shim.node, args: [shim.script, ...args], env: shim.env, verbatim: false, via: "node-shim" };
  return {
    file: commandInterpreter(options.env),
    args: ["/d", "/v:off", "/s", "/c", `"${[resolved, ...args].map(quoteCmdArgument).join(" ")}"`],
    env: options.env,
    verbatim: true,
    via: "cmd-shim",
  };
}

function isShim(file: string): boolean {
  return /\.(cmd|bat)$/i.test(file);
}

/** PATH/PATHEXT lookup without the current directory; a name with a directory part is taken relative to cwd. */
export async function resolveProgram(program: string, options: LaunchOptions): Promise<string | undefined> {
  const extensions = (envValue(options.env, "PATHEXT") ?? DEFAULT_PATHEXT)
    .split(";")
    .map((extension) => extension.trim().toLowerCase())
    .filter((extension) => RUNNABLE_EXTENSIONS.has(extension));
  const ownExtension = path.win32.extname(program).toLowerCase();
  const names = RUNNABLE_EXTENSIONS.has(ownExtension) ? [program] : extensions.map((extension) => `${program}${extension}`);
  if (/[\\/]/.test(program) || path.win32.isAbsolute(program)) {
    return firstFile(names.map((name) => path.win32.resolve(options.cwd, name)));
  }
  for (const directory of (envValue(options.env, "PATH") ?? "").split(";")) {
    const cleaned = directory.trim().replace(/^"|"$/g, "");
    if (cleaned === "" || !path.win32.isAbsolute(cleaned)) continue;
    const found = await firstFile(names.map((name) => path.win32.join(cleaned, name)));
    if (found !== undefined) return found;
  }
  return undefined;
}

async function firstFile(candidates: readonly string[]): Promise<string | undefined> {
  for (const candidate of candidates) {
    if (await isFile(candidate)) return candidate;
  }
  return undefined;
}

async function isFile(candidate: string): Promise<boolean> {
  try {
    return (await stat(candidate)).isFile();
  } catch {
    return false;
  }
}

function envValue(env: Readonly<Record<string, string>>, key: string): string | undefined {
  const match = Object.keys(env).find((candidate) => candidate.toUpperCase() === key);
  return match === undefined ? undefined : env[match];
}

function commandInterpreter(env: Readonly<Record<string, string>>): string {
  const root = envValue(env, "SYSTEMROOT") ?? process.env.SystemRoot ?? "C:\\Windows";
  return path.win32.join(root, "System32", "cmd.exe");
}

/**
 * One argument for a `cmd.exe /s /c` line that the target parses with the C runtime rules. The
 * whole argument is double-quoted so cmd treats `& | < > ^ ( )` literally; an embedded `"` is
 * doubled (`""` keeps cmd's quote state and is a literal quote to the C runtime), backslashes
 * before a quote or the closing quote are doubled, and every `%` becomes `%%cd:~,%` (cmd prints
 * the first `%` and expands `%cd:~,%` to nothing), so no `%name%` pair can ever form.
 */
export function quoteCmdArgument(argument: string): string {
  if (/[\r\n\0]/.test(argument)) throw new UnsafeLaunchError("an argument containing a line break or NUL cannot be passed through cmd.exe");
  let quoted = '"';
  let backslashes = 0;
  for (const character of argument) {
    if (character === "\\") {
      backslashes += 1;
      continue;
    }
    if (character === '"') {
      quoted += "\\".repeat(backslashes * 2) + '""';
    } else {
      quoted += "\\".repeat(backslashes) + (character === "%" ? "%%cd:~,%" : character);
    }
    backslashes = 0;
  }
  return `${quoted}${"\\".repeat(backslashes * 2)}"`;
}

interface NodeShim {
  readonly node: string;
  readonly script: string;
  readonly env: Readonly<Record<string, string>>;
}

/**
 * Every line an npm (cmd-shim) or pnpm (@zkochan/cmd-shim) node shim contains. A shim with any
 * other line (or a program other than node) is not recognised and runs through cmd.exe instead.
 */
const SHIM_LINES: readonly RegExp[] = [
  /^@?echo off$/i,
  /^::.*$/,
  /^goto start$/i,
  /^:find_dp0$/i,
  /^set dp0=%~dp0$/i,
  /^exit \/b$/i,
  /^:start$/i,
  /^@?setlocal$/i,
  /^call :find_dp0$/i,
  /^@?if exist "(%dp0%|%~dp0)\\node\.exe" \($/i,
  /^set "_prog=%dp0%\\node\.exe"$/i,
  /^\)\s*else\s*\($/i,
  /^set "_prog=node"$/i,
  /^@?set pathext=%pathext:;\.js;=;%$/i,
  /^\)$/,
  /^@if not defined node_path \($/i,
  /^@set "node_path=[^"]*"$/i,
];
const LAUNCH_LINE =
  /^(?:endLocal & goto #_undefined_# 2>NUL \|\| title %COMSPEC% & )?(?:"%_prog%"|"%~dp0\\node\.exe"|node)\s+"(?:%dp0%|%~dp0)\\?([^"%]+)"\s+%\*$/i;
const NODE_PATH_DEFAULT = /^@set "node_path=([^"%]*)"$/i;
const NODE_PATH_APPEND = /^@set "node_path=([^"]*)"$/i;

async function nodeShimTarget(shimPath: string, env: Readonly<Record<string, string>>): Promise<NodeShim | undefined> {
  let content: string;
  try {
    const info = await stat(shimPath);
    if (info.size > 64 * 1024) return undefined;
    content = await readFile(shimPath, "utf8");
  } catch {
    return undefined;
  }
  const scripts = new Map<string, string>();
  const nodePaths: string[] = [];
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === "") continue;
    const launch = LAUNCH_LINE.exec(line);
    if (launch !== null) {
      const target = launch[1] ?? "";
      scripts.set(target.toLowerCase(), target);
      continue;
    }
    if (!SHIM_LINES.some((pattern) => pattern.test(line))) return undefined;
    if (NODE_PATH_APPEND.test(line)) nodePaths.push(line);
  }
  if (scripts.size !== 1) return undefined;
  const shimDir = path.win32.dirname(shimPath);
  const script = path.win32.resolve(shimDir, [...scripts.values()][0] ?? "");
  if (!(await isFile(script))) return undefined;
  const nodeEnv = shimNodePath(nodePaths, env);
  if (nodeEnv === null) return undefined;
  const bundled = path.win32.join(shimDir, "node.exe");
  const node = (await isFile(bundled)) ? bundled : await resolveProgram("node", { cwd: shimDir, env });
  if (node === undefined || isShim(node)) return undefined;
  return { node, script, env: nodeEnv };
}

/**
 * The NODE_PATH a pnpm shim sets: the literal first value when NODE_PATH is unset, otherwise the
 * second value with `%NODE_PATH%` substituted. Null when the lines are not on that form.
 */
function shimNodePath(lines: readonly string[], env: Readonly<Record<string, string>>): Readonly<Record<string, string>> | null {
  if (lines.length === 0) return env;
  if (lines.length !== 2) return null;
  const unset = NODE_PATH_DEFAULT.exec(lines[0] ?? "")?.[1];
  const template = NODE_PATH_APPEND.exec(lines[1] ?? "")?.[1];
  if (unset === undefined || template === undefined) return null;
  const key = Object.keys(env).find((candidate) => candidate.toUpperCase() === "NODE_PATH");
  const current = key === undefined ? undefined : env[key];
  if (current === undefined || current === "") {
    return { ...withoutKey(env, key), NODE_PATH: unset };
  }
  if (template.replace(/%node_path%/gi, "").includes("%")) return null;
  return { ...withoutKey(env, key), NODE_PATH: template.replace(/%node_path%/gi, () => current) };
}

function withoutKey(env: Readonly<Record<string, string>>, key: string | undefined): Record<string, string> {
  const copy = { ...env };
  if (key !== undefined) delete copy[key];
  return copy;
}
